name: Add to Project Template
on:
  workflow_call:
    secrets:
      ADD_TO_PROJECT_PAT:
        required: true

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2
        with:
          add-to-project-url: Sabaoth-Cloud/.github/.github/workflows/add-to-project.yml@main